export interface PreparedBody {
  body: BodyInit | undefined
  /** Set alongside a body air serialised itself; never overrides one the caller set. */
  contentType?: string
  /**
   * The one header air removes rather than defers to. A `FormData` boundary is generated by
   * the runtime at send time, so no value a caller could write by hand is ever valid.
   */
  stripContentType?: boolean
  /**
   * Streaming a request body is a half-duplex exchange, and fetch refuses to send one
   * without being told so: "duplex option is required when sending a body".
   */
  duplex?: 'half'
}

/**
 * Decides how a `body` option reaches fetch. Anything that is already a valid `BodyInit` is
 * passed through untouched; everything else is JSON.
 */
export function prepareBody(body: unknown): PreparedBody {
  if (body === undefined || body === null) return { body: undefined }

  if (body instanceof FormData) return { body, stripContentType: true }

  if (body instanceof ReadableStream) return { body, duplex: 'half' }

  if (
    typeof body === 'string' ||
    body instanceof URLSearchParams ||
    body instanceof Blob ||
    body instanceof ArrayBuffer ||
    ArrayBuffer.isView(body)
  ) {
    return { body: body as BodyInit }
  }

  return { body: JSON.stringify(body), contentType: 'application/json' }
}
