export interface PreparedBody {
  body: BodyInit | undefined
  contentType?: string
  // A FormData boundary is generated by the runtime at send time, so no value the
  // caller could write by hand is ever valid — a caller-supplied one is removed
  // rather than kept, unlike every other header.
  stripContentType?: boolean
}

export function prepareBody(body: unknown): PreparedBody {
  if (body === undefined || body === null) return { body: undefined }

  if (body instanceof FormData) return { body, stripContentType: true }

  if (
    typeof body === 'string' ||
    body instanceof URLSearchParams ||
    body instanceof Blob ||
    body instanceof ArrayBuffer ||
    body instanceof ReadableStream ||
    ArrayBuffer.isView(body)
  ) {
    return { body: body as BodyInit }
  }

  return { body: JSON.stringify(body), contentType: 'application/json' }
}
